#no pruning old layout
[node.validator00]
seeds = ["seed01"]
discard_abci_responses = true
indexer = "null"

# pruning + compaction new layout
[node.validator01]
db_key_layout_version = "v2"
discard_abci_responses = true
indexer = "null"
retain_blocks = 100
compact = true
seeds = ["seed01"]

# pruning + compaction old layout
[node.validator02]
discard_abci_responses = true
retain_blocks = 100
indexer = "null"
compact = true
seeds = ["seed01"]

# pruning no compaction new layout
[node.validator03]
discard_abci_responses = true
db_key_layout_version = "v2"
retain_blocks = 100
indexer = "null"
seeds = ["seed01"]

# no pruning new layout
[node.validator04]
db_key_layout_version = "v2"
discard_abci_responses = true
indexer = "null"
seeds = ["seed01"]

# pruning no compaction old layout
[node.validator05]
discard_abci_responses = true
retain_blocks = 100
indexer = "null"
seeds = ["seed01"]

[node.seed01]
discard_abci_responses = true
indexer = "null"
mode = "seed"
