vote_extensions_enable_height = 1
vote_extension_size = 8192

[node.seed0]
mode = "seed"
persistent_peers = ["seed1", "seed2", "seed3", "seed4"]
[node.seed1]
mode = "seed"
persistent_peers = ["seed0", "seed2", "seed3", "seed4"]
[node.seed2]
mode = "seed"
persistent_peers = ["seed0", "seed1", "seed3", "seed4"]
[node.seed3]
mode = "seed"
persistent_peers = ["seed0", "seed1", "seed2", "seed4"]
[node.seed4]
mode = "seed"
persistent_peers = ["seed0", "seed1", "seed2", "seed3"]

[node.full00]
mode = "full"
seeds = ["seed0"]
[node.full01]
mode = "full"
seeds = ["seed1"]
[node.full02]
mode = "full"
seeds = ["seed2"]
[node.full03]
mode = "full"
seeds = ["seed3"]
[node.full04]
mode = "full"
seeds = ["seed4"]
[node.full05]
mode = "full"
seeds = ["seed0"]
[node.full06]
mode = "full"
seeds = ["seed1"]
[node.full07]
mode = "full"
seeds = ["seed2"]
[node.full08]
mode = "full"
seeds = ["seed3"]
[node.full09]
mode = "full"
seeds = ["seed4"]
[node.full10]
mode = "full"
seeds = ["seed0"]
[node.full11]
mode = "full"
seeds = ["seed1"]
[node.full12]
mode = "full"
seeds = ["seed2"]
[node.full13]
mode = "full"
seeds = ["seed3"]
[node.full14]
mode = "full"
seeds = ["seed4"]
[node.full15]
mode = "full"
seeds = ["seed0"]
[node.full16]
mode = "full"
seeds = ["seed1"]
[node.full17]
mode = "full"
seeds = ["seed2"]
[node.full18]
mode = "full"
seeds = ["seed3"]
[node.full19]
mode = "full"
seeds = ["seed4"]

[node.validator000]
seeds = ["seed0"]
[node.validator001]
seeds = ["seed1"]
[node.validator002]
seeds = ["seed2"]
[node.validator003]
seeds = ["seed3"]
[node.validator004]
seeds = ["seed4"]
[node.validator005]
seeds = ["seed0"]
[node.validator006]
seeds = ["seed1"]
[node.validator007]
seeds = ["seed2"]
[node.validator008]
seeds = ["seed3"]
[node.validator009]
seeds = ["seed4"]
[node.validator010]
seeds = ["seed0"]
[node.validator011]
seeds = ["seed1"]
[node.validator012]
seeds = ["seed2"]
[node.validator013]
seeds = ["seed3"]
[node.validator014]
seeds = ["seed4"]
[node.validator015]
seeds = ["seed0"]
[node.validator016]
seeds = ["seed1"]
[node.validator017]
seeds = ["seed2"]
[node.validator018]
seeds = ["seed3"]
[node.validator019]
seeds = ["seed4"]
[node.validator020]
seeds = ["seed0"]
[node.validator021]
seeds = ["seed1"]
[node.validator022]
seeds = ["seed2"]
[node.validator023]
seeds = ["seed3"]
[node.validator024]
seeds = ["seed4"]
[node.validator025]
seeds = ["seed0"]
[node.validator026]
seeds = ["seed1"]
[node.validator027]
seeds = ["seed2"]
[node.validator028]
seeds = ["seed3"]
[node.validator029]
seeds = ["seed4"]
[node.validator030]
seeds = ["seed0"]
[node.validator031]
seeds = ["seed1"]
[node.validator032]
seeds = ["seed2"]
[node.validator033]
seeds = ["seed3"]
[node.validator034]
seeds = ["seed4"]
[node.validator035]
seeds = ["seed0"]
[node.validator036]
seeds = ["seed1"]
[node.validator037]
seeds = ["seed2"]
[node.validator038]
seeds = ["seed3"]
[node.validator039]
seeds = ["seed4"]
[node.validator040]
seeds = ["seed0"]
[node.validator041]
seeds = ["seed1"]
[node.validator042]
seeds = ["seed2"]
[node.validator043]
seeds = ["seed3"]
[node.validator044]
seeds = ["seed4"]
[node.validator045]
seeds = ["seed0"]
[node.validator046]
seeds = ["seed1"]
[node.validator047]
seeds = ["seed2"]
[node.validator048]
seeds = ["seed3"]
[node.validator049]
seeds = ["seed4"]
[node.validator050]
seeds = ["seed0"]
[node.validator051]
seeds = ["seed1"]
[node.validator052]
seeds = ["seed2"]
[node.validator053]
seeds = ["seed3"]
[node.validator054]
seeds = ["seed4"]
[node.validator055]
seeds = ["seed0"]
[node.validator056]
seeds = ["seed1"]
[node.validator057]
seeds = ["seed2"]
[node.validator058]
seeds = ["seed3"]
[node.validator059]
seeds = ["seed4"]
[node.validator060]
seeds = ["seed0"]
[node.validator061]
seeds = ["seed1"]
[node.validator062]
seeds = ["seed2"]
[node.validator063]
seeds = ["seed3"]
[node.validator064]
seeds = ["seed4"]
[node.validator065]
seeds = ["seed0"]
[node.validator066]
seeds = ["seed1"]
[node.validator067]
seeds = ["seed2"]
[node.validator068]
seeds = ["seed3"]
[node.validator069]
seeds = ["seed4"]
[node.validator070]
seeds = ["seed0"]
[node.validator071]
seeds = ["seed1"]
[node.validator072]
seeds = ["seed2"]
[node.validator073]
seeds = ["seed3"]
[node.validator074]
seeds = ["seed4"]
[node.validator075]
seeds = ["seed0"]
[node.validator076]
seeds = ["seed1"]
[node.validator077]
seeds = ["seed2"]
[node.validator078]
seeds = ["seed3"]
[node.validator079]
seeds = ["seed4"]
[node.validator080]
seeds = ["seed0"]
[node.validator081]
seeds = ["seed1"]
[node.validator082]
seeds = ["seed2"]
[node.validator083]
seeds = ["seed3"]
[node.validator084]
seeds = ["seed4"]
[node.validator085]
seeds = ["seed0"]
[node.validator086]
seeds = ["seed1"]
[node.validator087]
seeds = ["seed2"]
[node.validator088]
seeds = ["seed3"]
[node.validator089]
seeds = ["seed4"]
[node.validator090]
seeds = ["seed0"]
[node.validator091]
seeds = ["seed1"]
[node.validator092]
seeds = ["seed2"]
[node.validator093]
seeds = ["seed3"]
[node.validator094]
seeds = ["seed4"]
[node.validator095]
seeds = ["seed0"]
[node.validator096]
seeds = ["seed1"]
[node.validator097]
seeds = ["seed2"]
[node.validator098]
seeds = ["seed3"]
[node.validator099]
seeds = ["seed4"]
[node.validator100]
seeds = ["seed0"]
[node.validator101]
seeds = ["seed1"]
[node.validator102]
seeds = ["seed2"]
[node.validator103]
seeds = ["seed3"]
[node.validator104]
seeds = ["seed4"]
[node.validator105]
seeds = ["seed0"]
[node.validator106]
seeds = ["seed1"]
[node.validator107]
seeds = ["seed2"]
[node.validator108]
seeds = ["seed3"]
[node.validator109]
seeds = ["seed4"]
[node.validator110]
seeds = ["seed0"]
[node.validator111]
seeds = ["seed1"]
[node.validator112]
seeds = ["seed2"]
[node.validator113]
seeds = ["seed3"]
[node.validator114]
seeds = ["seed4"]
[node.validator115]
seeds = ["seed0"]
[node.validator116]
seeds = ["seed1"]
[node.validator117]
seeds = ["seed2"]
[node.validator118]
seeds = ["seed3"]
[node.validator119]
seeds = ["seed4"]
[node.validator120]
seeds = ["seed0"]
[node.validator121]
seeds = ["seed1"]
[node.validator122]
seeds = ["seed2"]
[node.validator123]
seeds = ["seed3"]
[node.validator124]
seeds = ["seed4"]
[node.validator125]
seeds = ["seed0"]
[node.validator126]
seeds = ["seed1"]
[node.validator127]
seeds = ["seed2"]
[node.validator128]
seeds = ["seed3"]
[node.validator129]
seeds = ["seed4"]
[node.validator130]
seeds = ["seed0"]
[node.validator131]
seeds = ["seed1"]
[node.validator132]
seeds = ["seed2"]
[node.validator133]
seeds = ["seed3"]
[node.validator134]
seeds = ["seed4"]
[node.validator135]
seeds = ["seed0"]
[node.validator136]
seeds = ["seed1"]
[node.validator137]
seeds = ["seed2"]
[node.validator138]
seeds = ["seed3"]
[node.validator139]
seeds = ["seed4"]
[node.validator140]
seeds = ["seed0"]
[node.validator141]
seeds = ["seed1"]
[node.validator142]
seeds = ["seed2"]
[node.validator143]
seeds = ["seed3"]
[node.validator144]
seeds = ["seed4"]
[node.validator145]
seeds = ["seed0"]
[node.validator146]
seeds = ["seed1"]
[node.validator147]
seeds = ["seed2"]
[node.validator148]
seeds = ["seed3"]
[node.validator149]
seeds = ["seed4"]
[node.validator150]
seeds = ["seed0"]
[node.validator151]
seeds = ["seed1"]
[node.validator152]
seeds = ["seed2"]
[node.validator153]
seeds = ["seed3"]
[node.validator154]
seeds = ["seed4"]
[node.validator155]
seeds = ["seed0"]
[node.validator156]
seeds = ["seed1"]
[node.validator157]
seeds = ["seed2"]
[node.validator158]
seeds = ["seed3"]
[node.validator159]
seeds = ["seed4"]
[node.validator160]
seeds = ["seed0"]
[node.validator161]
seeds = ["seed1"]
[node.validator162]
seeds = ["seed2"]
[node.validator163]
seeds = ["seed3"]
[node.validator164]
seeds = ["seed4"]
[node.validator165]
seeds = ["seed0"]
[node.validator166]
seeds = ["seed1"]
[node.validator167]
seeds = ["seed2"]
[node.validator168]
seeds = ["seed3"]
[node.validator169]
seeds = ["seed4"]
[node.validator170]
seeds = ["seed0"]
[node.validator171]
seeds = ["seed1"]
[node.validator172]
seeds = ["seed2"]
[node.validator173]
seeds = ["seed3"]
[node.validator174]
seeds = ["seed4"]
