- name: base
  hosts: validators
  gather_facts: yes
  become_method: sudo
 
  tasks:
    - name: install git
      ansible.builtin.apt:
        name: git
        state: latest
      become: yes
    - name: install gcc
      ansible.builtin.apt:
        name: gcc
        state: latest
      become: yes
    - name: install go
      ansible.builtin.apt:
        name: golang-go
        state: latest
      become: yes
