- name: base
  hosts: validators,prometheus,loadrunners,ephemeral
  gather_facts: yes
  become_method: sudo
  vars:
    ansible_host_key_checking: false

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 60
      become: yes
    - name: restart systemd journal
      ansible.builtin.systemd:
        name: systemd-journald
        state: restarted
      become: yes
    - name: install deps
      ansible.builtin.apt:
        name:
          - git
          - gcc
          - golang-1.19-go
          - prometheus
          - prometheus-node-exporter
          - ntp
          - ntpstat
          - jq
          - ufw
          - tmux
        state: latest
      become: yes
    - name: ufw - allow all incoming traffic from private IPs
      community.general.ufw:
        rule: allow
        direction: in
        to: "{{vpc_subnet}}"
      become: yes
    - name: ufw - allow all outgoing traffic to private IPs
      community.general.ufw:
        rule: allow
        direction: out
        to: "{{vpc_subnet}}"
      become: yes
    - name: ufw - allow outgoing http traffic
      community.general.ufw:
        rule: allow
        direction: out
        to: 0.0.0.0/0
        to_port: http
        proto: tcp
      become: yes
    - name: ufw - allow outgoing https traffic
      community.general.ufw:
        rule: allow
        direction: out
        to: 0.0.0.0/0
        to_port: https
        proto: tcp
      become: yes
    - name: ufw - allow outgoing dns traffic
      community.general.ufw:
        rule: allow
        direction: out
        to: 0.0.0.0/0
        name: dns
      become: yes
    - name: ufw - allow incoming ssh
      community.general.ufw:
        rule: allow
        direction: in
        to: 0.0.0.0/0
        to_port: ssh
        proto: tcp
      become: yes
    - name: ufw - allow incoming Comet RPC
      community.general.ufw:
        rule: allow
        direction: in
        to: 0.0.0.0/0
        to_port: 26657
        proto: tcp
      become: yes
    - name: ufw - allow incoming Comet gRPC
      community.general.ufw:
        rule: allow
        direction: in
        to: 0.0.0.0/0
        to_port: 26670
        proto: tcp
      become: yes
    - name: ufw - enable
      community.general.ufw:
        state: enabled
      become: yes
    - name: ufw - default deny incoming traffic
      community.general.ufw:
        default: deny
        direction: incoming
      become: yes
    - name: ufw - default deny outgoing traffic
      community.general.ufw:
        default: deny
        direction: outgoing
      become: yes
