- name: base
  hosts: validators,prometheus
  gather_facts: yes
  become_method: sudo
  vars:
    ansible_host_key_checking: false
 
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 60
    - name: install deps
      ansible.builtin.apt:
        name:
          - git
          - gcc
          - golang-1.17-go
          - prometheus
        state: latest
      become: yes
