- name: base
  hosts: validators,prometheus,loadrunners,ephemeral
  gather_facts: yes
  become_method: sudo
  vars:
    ansible_host_key_checking: false

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 60
    - name: restart systemd journal
      ansible.builtin.systemd:
        name: systemd-journald
        state: restarted
      become: yes
    - name: install deps
      ansible.builtin.apt:
        name:
          - git
          - gcc
          - golang-1.19-go
          - prometheus
          - prometheus-node-exporter
          - ntp
          - ntpstat
          - jq
          - tmux
        state: latest
      become: yes
