- name: base
  hosts: validators
  gather_facts: yes
  become_method: sudo
  vars:
    ansible_host_key_checking: false
 
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 60
    - name: install git
      ansible.builtin.apt:
        name: git
        state: latest
      become: yes
    - name: install gcc
      ansible.builtin.apt:
        name: gcc
        state: latest
      become: yes
    - name: install go
      ansible.builtin.apt:
        name: golang-1.17-go
        state: latest
      become: yes
