- name: initialize app
  hosts: validators
  become: false
  gather_facts: yes
  hosts: validators
  vars:
    tm_home: /root/.testapp/
    ansible_host_key_checking: false
 
  tasks:
    - name: copy configuration files
      ansible.builtin.copy:
        src: ./testnet/{{ hostvars[inventory_hostname].name }}/config/config.toml
        dest: "{{ tm_home }}/config/config.toml"
    - name: restart app
      ansible.builtin.systemd:
        name: testappd
        state: restarted
      become: yes
