- name: initialize app
  hosts: validators
  become: false
  gather_facts: yes
  hosts: validators
  vars:
    tm_home: /root/.celestia-app/
    ansible_host_key_checking: false
 
  tasks:
    - name: clone the networks file
      ansible.builtin.git:
        repo: https://github.com/celestiaorg/networks
        dest: "{{ ansible_user_dir }}/networks"
        version: master
    - name: init celestia node
      shell: "{{ ansible_user_dir }}/go/bin/celestia-appd init interchain --chain-id mamaki"
    - name: copy over networks file
      ansible.builtin.copy:
        src: "{{ ansible_user_dir }}/networks/mamaki/genesis.json"
        dest: "{{ tm_home }}/config/genesis.json"
        remote_src: yes
        force: yes
    - name: add bootstrap peers to config
      shell: |
        BOOTSTRAP_PEERS=$(curl -sL https://raw.githubusercontent.com/celestiaorg/networks/master/mamaki/bootstrap-peers.txt | tr -d '\n')
        sed -i.bak -e "s/^bootstrap-peers *=.*/bootstrap-peers = \"$BOOTSTRAP_PEERS\"/" "{{ tm_home}}/config/config.toml"
    - name: update prometheus setting
      shell: |
        sed -i.bak -e "s/^prometheus *=.*/prometheus = true/" "{{ tm_home}}/config/config.toml"
