- name: initialize app
  hosts: validators,ephemeral
  become: false
  gather_facts: yes
  vars:
    tm_home: /root/.testapp/
    ansible_host_key_checking: false
 
  tasks:
    - name: copy configuration files
      ansible.builtin.copy:
        src: ./testnet/{{ hostvars[inventory_hostname].name }}/
        dest: "{{ tm_home }}/"
