- name: initialize app
  hosts: validators
  become: false
  gather_facts: yes
  hosts: validators
  vars: 
    tm_home: /root/.testapp/
    ansible_host_key_checking: false
 
  tasks:
    - name: copy configuration files
      ansible.builtin.copy:
        src: ./testnet-configs/{{ hostvars[inventory_hostname].name }}/
        dest: "{{ tm_home }}/"
