- name: initialize app
  hosts: validators,ephemeral
  become: false
  gather_facts: yes
  vars:
    tm_home: /root/.testapp/
    ansible_host_key_checking: false
    local_config_dir: ./full-testnet/{{ hostvars[inventory_hostname].name }}
 
  tasks:
    - name: copy configuration files
      ansible.builtin.copy:
        src: "{{ local_config_dir }}/"
        dest: "{{ tm_home }}/"
