- name: Initialize loadrunners
  become: false
  gather_facts: yes
  hosts: loadrunners
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 60
    - name: Install deps
      ansible.builtin.apt:
        name:
          - jq
          - tmux
        state: latest
      become: yes
    - name: Check if load tool exists
      stat:
        path: /root/go/bin/load
      register: load_tool
    - name: Install load tool
      ansible.builtin.command: /usr/lib/go-1.19/bin/go install
      args:
        chdir: /root/cometbft/test/loadtime/cmd/load/
      when: not load_tool.stat.exists
    - name: Copy script files
      copy: 
        src: "{{ item.src }}" 
        dest: /root
      loop:
        - src: scripts/200-node-loadscript.sh
        - src: scripts/rotating-loadscript.sh
      become: yes
