- name: create prometheus
  become: false
  gather_facts: yes
  hosts: prometheus
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: create unit file
      template:
        src: templates/prometheus.service.j2
        dest: /lib/systemd/system/prometheus.service
      become: yes
    - name: create config
      template:
        src: templates/prometheus.yml.j2
        dest: /etc/prometheus/prometheus.yml
      become: yes
    - name: reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
      become: yes
    - name: start the systemd-unit
      ansible.builtin.systemd:
        name: prometheus
        state: started
        enabled: yes
