- name: prometheus node exporter
  hosts: validators,prometheus,loadrunners,ephemeral
  gather_facts: yes
  become_method: sudo
  vars:
    ansible_host_key_checking: false

  tasks:
    - name: add node-exporter systemd unit file
      ansible.builtin.copy:
        src: templates/prometheus-node-exporter.service
        dest: /etc/prometheus/prometheus-node-exporter.service
      become: yes
    - name: start the systemd unit
      ansible.builtin.systemd:
        name: prometheus-node-exporter
        state: started
        daemon_reload: yes
        enabled: yes
