- name: remove testapp data
  hosts: validators
  become_method: sudo
  gather_facts: yes
  vars:
    cmt_home: /root/.testapp/
 
  tasks:
    - name: stop app
      ansible.builtin.systemd:
        name: testappd
        state: stopped
      become: yes
    - name: delete cmt data
      ansible.builtin.file:
        path: "{{ cmt_home }}"
        state: absent
      become: yes
    - name: delete app data
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/data"
        state: absent
      become: yes
