- name: restart testapp
  hosts: validators
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_host_key_checking: false
 
  tasks:
    - name: restart app
      ansible.builtin.systemd:
        name: testappd
        state: restarted
      become: yes
