- name: update testapp
  hosts: validators,ephemeral
  become_method: sudo
  gather_facts: yes
 
  tasks:
    - name: restart app
      ansible.builtin.systemd:
        name: systemd-journald
        state: restarted
      become: yes
