- name: retrieve blockstore
  hosts: validators
  become: false
  gather_facts: yes
  vars:
    tm_home: /root/.testapp/
    ansible_host_key_checking: false
  tasks:
    - name: stop app
      ansible.builtin.systemd:
        name: testappd
        state: stopped
      become: yes
    - name: Delete old zip
      ansible.builtin.file:
        path: "{{ tm_home }}/data/blockstore.db.zip"
        state: absent
    - name: Zip the blockstore directory
      archive:
        path: "{{ tm_home }}/data/blockstore.db"
        format: zip
        dest: "{{ tm_home }}/data/blockstore.db.zip"
    - name: Fetch the blockstore
      ansible.builtin.fetch:
        src: "{{ tm_home }}/data/blockstore.db.zip"
        dest: "{{dir}}/{{ hostvars[inventory_hostname].name }}/blockstore.db.zip"
        flat: yes
    - name: start the systemd-unit
      ansible.builtin.systemd:
        name: testappd
        state: started
      become: yes
