- name: stop runload
  become: false
  gather_facts: yes
  hosts: validators
  vars:
    ansible_host_key_checking: false
  tasks:
    - name: start the systemd-unit
      ansible.builtin.systemd:
        state: stopped
        name: runload
