- name: start testapp
  hosts: validators,ephemeral
  gather_facts: yes
 
  tasks:
  - name: stop the systemd-unit
    ansible.builtin.systemd:
      name: testappd
      state: stopped
      enabled: yes
