- name: build testapp
  hosts: validators,ephemeral
  become_method: sudo
  gather_facts: true

  tasks:
    - ansible.builtin.import_tasks: tasks/testapp-copy-config-files.yaml
      when: "'ephemeral' not in group_names" # initially there are no config files for ephemeral nodes

    - ansible.builtin.import_tasks: tasks/testapp-clone-repo.yaml

    - ansible.builtin.import_tasks: tasks/testapp-build.yaml

    - ansible.builtin.import_tasks: tasks/testapp-update-unit-file.yaml
