- name: initialize app
  hosts: validators
  become: false
  gather_facts: yes
  vars:
    cmt_home: /root/.testapp/
    ansible_host_key_checking: false

  tasks:
    - name: copy configuration files
      ansible.builtin.copy:
        src: ./testnet/{{ hostvars[inventory_hostname].name }}/
        dest: "{{ cmt_home }}/"
    - name: ufw - allow outgoing ntp
      community.general.ufw:
        rule: allow
        direction: out
        to_port: '123'
        proto: udp
