- name: start testapp
  hosts: validators,ephemeral
  gather_facts: yes
  vars:
    ansible_host_key_checking: false
 
  tasks:
  - name: stop the systemd-unit
    ansible.builtin.systemd:
      name: testappd
      state: stopped
      enabled: yes
