- name: remove testapp data
  hosts: validators
  become_method: sudo
  gather_facts: true

  tasks:
    - ansible.builtin.import_tasks: tasks/testapp-stop.yaml
    - ansible.builtin.import_tasks: tasks/testapp-remove-data.yaml
