- name: re-init testapp
  hosts: validators,ephemeral
  become_method: sudo
  gather_facts: true

  tasks:
    - ansible.builtin.import_tasks: tasks/testapp-stop.yaml
    - ansible.builtin.import_tasks: tasks/testapp-remove-data.yaml
    - ansible.builtin.import_tasks: tasks/testapp-copy-config-files.yaml
    - ansible.builtin.import_tasks: tasks/testapp-start.yaml
