- name: build testapp
  hosts: validators,ephemeral,loadrunners
  become_method: sudo
  gather_facts: true

  tasks:
    - ansible.builtin.import_tasks: tasks/testapp-copy-config-files.yaml
      # no config files for loadrunners
      when: "'loadrunners' not in group_names"

    - ansible.builtin.import_tasks: tasks/testapp-clone-repo.yaml

    - ansible.builtin.import_tasks: tasks/testapp-build.yaml

    - ansible.builtin.import_tasks: tasks/testapp-update-unit-file.yaml
