- name: re-init testapp
  hosts: ephemeral,validators
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_host_key_checking: false
    cmt_home: /root/.testapp/
    testnet_dir: ./testnet

  # TODO: the first three tasks are testapp-remove-data.yaml
  tasks:
    - name: stop app
      ansible.builtin.systemd:
        name: testappd
        state: stopped
      become: yes
    
    - name: stop storage collection script
      shell: "kill $(ps aux | grep [s]torage_footprint | awk '{print $2}')"

    - name: delete data in home directory
      ansible.builtin.file:
        path: "{{ cmt_home }}"
        state: absent
      become: yes

    - name: delete app data
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/data"
        state: absent
      become: yes

    - name: copy configuration files
      ansible.builtin.copy:
        src: "{{ testnet_dir }}/{{ hostvars[inventory_hostname].name }}/"
        dest: "{{ cmt_home }}/"

    - name: start the systemd-unit
      ansible.builtin.systemd:
        name: testappd
        state: started
        enabled: yes

    - name: copy storage script
      ansible.builtin.copy:
        src: scripts/get_storage_footprint.sh
        dest: "{{ cmt_home }}"
        mode: u+rwx
    - name: update storage footprint file
      shell: "screen -dm -S storage {{ cmt_home }}/get_storage_footprint.sh {{ cmt_home }}"
