- name: start testapp
  hosts: validators
  gather_facts: yes
  vars:
    ansible_host_key_checking: false

  tasks:
  - name: start the systemd-unit
    ansible.builtin.systemd:
      name: testappd
      state: started
      enabled: yes
